server:
  port: 8081
  compression:
    enabled: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: cjclcx529
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: guest
    password: guest
    host: 1.117.90.202
    publisher-returns: true
  redis:
    host: 127.0.0.1
    database: 10
    port: 6379
    password:
    timeout:
  cache:
    cache-names: menus_cache
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-on-validation-error: false
fastdfs:
  nginx:
    host: http://1.117.90.202/
logging:
  level:
    org.javaboy.vhr.mappe: debug
